import os

API_BASE_URL = 'http://v0.ovapi.nl'
ENDPOINT = 'line'
PER_LINE_ENDPOINT_REQUEST = f"{API_BASE_URL}/{ENDPOINT}/"

WAIT_EXPONENTIAL_MIN = 4
WAIT_EXPONENTIAL_MAX = 10
WAIT_EXPONENTIAL_MULTIPLAYER = 1
MAX_ATTEPTS = 100

NAN_VALUE = '-'
MISSING_VALUE = '-'

DATABASE_USER = os.environ.get('DATABASE_USER', 'postgres')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD', 'postgres')
DATABASE_NAME = os.environ.get('DATABASE_NAME', 'postgres')
DATABASE_HOST = os.environ.get('DATABASE_HOST', '0.0.0.0')
DATABASE_PORT = 5432

